//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puremvc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("puremvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item name=&quot;name&quot; value=&quot;human&quot; /&gt;
        ///  &lt;item name=&quot;he&quot; value=&quot;somebody&quot; /&gt;
        ///  &lt;item name=&quot;she&quot; value=&quot;somebody&quot; /&gt;
        ///  &lt;item name=&quot;it&quot; value=&quot;something&quot; /&gt;
        ///  &lt;item name=&quot;they&quot; value=&quot;something&quot; /&gt;
        ///  &lt;item name=&quot;age&quot; value=&quot;unknown&quot; /&gt;
        ///  &lt;item name=&quot;birthday&quot; value=&quot;unknown&quot; /&gt;
        ///  &lt;item name=&quot;boyfriend&quot; value=&quot;unknown&quot; /&gt;
        ///  &lt;item name=&quot;brother&quot; value=&quot;unknown&quot; /&gt;
        ///  &lt;item name=&quot;cat&quot; value=&quot;unknown&quot; /&gt;
        ///  &lt;item name=&quot;does&quot; value=&quot;unknown&quot; /&gt;
        ///  &lt;item name=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultPredicates {
            get {
                return ResourceManager.GetString("DefaultPredicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exiting {
            get {
                object obj = ResourceManager.GetObject("Exiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap frown {
            get {
                object obj = ResourceManager.GetObject("frown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item name=&quot; HE &quot; value=&quot; she &quot; /&gt;
        ///  &lt;item name=&quot; SHE &quot; value=&quot; he &quot; /&gt;
        ///  &lt;item name=&quot; TO HIM &quot; value=&quot; to her &quot; /&gt;
        ///  &lt;item name=&quot; FOR HIM &quot; value=&quot; for her &quot; /&gt;
        ///  &lt;item name=&quot; WITH HIM &quot; value=&quot; with her &quot; /&gt;
        ///  &lt;item name=&quot; ON HIM &quot; value=&quot; on her &quot; /&gt;
        ///  &lt;item name=&quot; IN HIM &quot; value=&quot; in her &quot; /&gt;
        ///  &lt;item name=&quot; TO HER &quot; value=&quot; to him &quot; /&gt;
        ///  &lt;item name=&quot; FOR HER &quot; value=&quot; for him &quot; /&gt;
        ///  &lt;item name=&quot; WITH HER &quot; value=&quot; with him &quot; /&gt;
        ///  &lt;item name=&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenderSubstitutions {
            get {
                return ResourceManager.GetString("GenderSubstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap idu0 {
            get {
                object obj = ResourceManager.GetObject("idu0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Listening {
            get {
                object obj = ResourceManager.GetObject("Listening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meh {
            get {
                object obj = ResourceManager.GetObject("meh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotListening {
            get {
                object obj = ResourceManager.GetObject("NotListening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item name=&quot; WITH YOU &quot; value=&quot; with me &quot; /&gt;
        ///  &lt;item name=&quot; WITH ME &quot; value=&quot; with you &quot; /&gt;
        ///  &lt;item name=&quot; TO YOU &quot; value=&quot; to me &quot; /&gt;
        ///  &lt;item name=&quot; TO ME &quot; value=&quot; to you &quot; /&gt;
        ///  &lt;item name=&quot; OF YOU &quot; value=&quot; of me &quot; /&gt;
        ///  &lt;item name=&quot; OF ME &quot; value=&quot; of you &quot; /&gt;
        ///  &lt;item name=&quot; FOR YOU &quot; value=&quot; for me &quot; /&gt;
        ///  &lt;item name=&quot; FOR ME &quot; value=&quot; for you &quot; /&gt;
        ///  &lt;item name=&quot; GIVE YOU &quot; value=&quot; give me &quot; /&gt;
        ///  &lt;item name=&quot; GIVE ME &quot; value=&quot; give you &quot; /&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Person2Substitutions {
            get {
                return ResourceManager.GetString("Person2Substitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item name=&quot; I WAS &quot; value=&quot; he or she was &quot; /&gt;
        ///  &lt;item name=&quot; I AM &quot; value=&quot; he or she is &quot; /&gt;
        ///  &lt;item name=&quot; I &quot; value=&quot; he or she &quot; /&gt;
        ///  &lt;item name=&quot; HE WAS &quot; value=&quot; I was &quot; /&gt;
        ///  &lt;item name=&quot; SHE WAS &quot; value=&quot; I was &quot; /&gt;
        ///  &lt;item name=&quot; ME &quot; value=&quot; him or her &quot; /&gt;
        ///  &lt;item name=&quot; MY &quot; value=&quot; his or her &quot; /&gt;
        ///  &lt;item name=&quot; MYSELF &quot; value=&quot; him or herself &quot; /&gt;
        ///&lt;/root&gt;
        ///.
        /// </summary>
        internal static string PersonSubstitutions {
            get {
                return ResourceManager.GetString("PersonSubstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile {
            get {
                object obj = ResourceManager.GetObject("smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Speaking {
            get {
                object obj = ResourceManager.GetObject("Speaking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item value=&quot;.&quot;/&gt;
        ///  &lt;item value=&quot;!&quot;/&gt;
        ///  &lt;item value=&quot;?&quot;/&gt;
        ///  &lt;item value=&quot;;&quot;/&gt;
        ///&lt;/root&gt;
        ///.
        /// </summary>
        internal static string Splitters {
            get {
                return ResourceManager.GetString("Splitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item name=&quot;=REPLY&quot; value=&quot;&quot; /&gt;
        ///  &lt;item name=&quot;NAME=RESET&quot; value=&quot;&quot; /&gt;
        ///  &lt;item name=&quot;:-)&quot; value=&quot; smile &quot; /&gt;
        ///  &lt;item name=&quot;:)&quot; value=&quot; smile &quot; /&gt;
        ///  &lt;item name=&quot;,)&quot; value=&quot; smile &quot; /&gt;
        ///  &lt;item name=&quot;;)&quot; value=&quot; smile &quot; /&gt;
        ///  &lt;item name=&quot;;-)&quot; value=&quot; smile &quot; /&gt;
        ///  &lt;item name=&quot;&amp;quot;&quot; value=&quot;&quot; /&gt;
        ///  &lt;item name=&quot;/&quot; value=&quot; &quot; /&gt;
        ///  &lt;item name=&quot;&amp;gt;&quot; value=&quot; gt &quot; /&gt;
        ///  &lt;item name=&quot;&amp;lt;&quot; value=&quot; lt &quot; /&gt;
        ///  &lt;item name=&quot;(&quot; value=&quot; &quot; /&gt;
        ///  &lt;item name=&quot;)&quot; value=&quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Substitutions {
            get {
                return ResourceManager.GetString("Substitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Thinking {
            get {
                object obj = ResourceManager.GetObject("Thinking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream tng_viewscreen_on {
            get {
                return ResourceManager.GetStream("tng_viewscreen_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trashW {
            get {
                object obj = ResourceManager.GetObject("trashW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream UI_button_2 {
            get {
                return ResourceManager.GetStream("UI_button_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream UI_button_3 {
            get {
                return ResourceManager.GetStream("UI_button_3", resourceCulture);
            }
        }
    }
}
